//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Req_App_table
    {
        public int Admin_Approval_ID { get; set; }
        public int Admin_Id { get; set; }
        public int Request_Id { get; set; }
        public string State { get; set; }
    
        public virtual Admin_table Admin_table { get; set; }
        public virtual Request_table Request_table { get; set; }
    }
}
