//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Following_table
    {
        public int follow_id { get; set; }
        public int User_id { get; set; }
        public int Vendor_id { get; set; }
    
        public virtual User_table User_table { get; set; }
        public virtual User_table User_table1 { get; set; }
    }
}
