//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CraftsEntities : DbContext
    {
        public CraftsEntities()
            : base("name=CraftsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Req_App_table> Admin_Req_App_table { get; set; }
        public virtual DbSet<Admin_table> Admin_table { get; set; }
        public virtual DbSet<Category_table> Category_table { get; set; }
        public virtual DbSet<Comments_Table> Comments_Table { get; set; }
        public virtual DbSet<Following_table> Following_table { get; set; }
        public virtual DbSet<Message_table> Message_table { get; set; }
        public virtual DbSet<Order_table> Order_table { get; set; }
        public virtual DbSet<OrderDetails_table> OrderDetails_table { get; set; }
        public virtual DbSet<Posts_table> Posts_table { get; set; }
        public virtual DbSet<Product_table> Product_table { get; set; }
        public virtual DbSet<Request_table> Request_table { get; set; }
        public virtual DbSet<Subscribtion_table> Subscribtion_table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_table> Type_table { get; set; }
        public virtual DbSet<User_table> User_table { get; set; }
    }
}
