//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_table()
        {
            this.OrderDetails_table = new HashSet<OrderDetails_table>();
        }
    
        public int Order_Id { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Order_Address { get; set; }
        public int Order_Phone { get; set; }
        public double Expected_Price { get; set; }
        public int User_Id { get; set; }
    
        public virtual User_table User_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails_table> OrderDetails_table { get; set; }
    }
}
