//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts_table()
        {
            this.Comments_Table = new HashSet<Comments_Table>();
        }
    
        public int Post_id { get; set; }
        public string Post_body { get; set; }
        public int User_id { get; set; }
        public byte[] Post_pic { get; set; }
        public System.DateTime Post_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments_Table> Comments_Table { get; set; }
        public virtual User_table User_table { get; set; }
    }
}
