//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview_table
    {
        public int review_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string review_body { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
    
        public virtual Product_table Product_table { get; set; }
        public virtual User_table User_table { get; set; }
    }
}
