//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_table
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public double Product_Price { get; set; }
        public int Cat_id { get; set; }
        public int Vendor_id { get; set; }
        public string State { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime Add_Date { get; set; }
    
        public virtual Category_table Category_table { get; set; }
    }
}
