//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request_table()
        {
            this.Admin_Req_App_table = new HashSet<Admin_Req_App_table>();
        }
    
        public int Request_Id { get; set; }
        public System.DateTime Request_Date { get; set; }
        public int User_Id { get; set; }
        public string reqState { get; set; }
        public string Full_Name { get; set; }
        public int National_ID { get; set; }
        public string Seller_info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Req_App_table> Admin_Req_App_table { get; set; }
        public virtual User_table User_table { get; set; }
    }
}
