//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_table()
        {
            this.Following_table = new HashSet<Following_table>();
            this.Following_table1 = new HashSet<Following_table>();
            this.Order_table = new HashSet<Order_table>();
            this.Product_table = new HashSet<Product_table>();
            this.Request_table = new HashSet<Request_table>();
            this.Subscribtion_table = new HashSet<Subscribtion_table>();
        }
    
        public int User_Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string User_Name { get; set; }
        public string User_Email { get; set; }
        public string Password { get; set; }
        public int PhoneNumber { get; set; }
        public int SSN { get; set; }
        public int Type_id { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string Gender { get; set; }
        public string Bio { get; set; }
        public double rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Following_table> Following_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Following_table> Following_table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_table> Order_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_table> Product_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_table> Request_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribtion_table> Subscribtion_table { get; set; }
        public virtual Type_table Type_table { get; set; }
    }
}
